version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_DB: "management"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"